#!/bin/bash

# declare variable
a=123
echo "a=${a}"

# arr
arr=(6 5 4 3 2 1)

echo "arr = ${arr[@]}"
echo "arr[3] = ${arr[3]}"
echo "arr.length =  ${#arr[@]}"

for((i=0; i<${#arr[@]}; i++));
do 
echo "arr[${i}] = ${arr[i]}"
done

# caclute
sum=$(expr "1+2")
echo "1+2 = ${sum}"


# string 
name="sunfeilong"
echo ${name}
echo ${#name}
echo "my name is ${name}"
echo ${name:0:5} # sunf
# echo `expr index "${name}" n`
echo $(expr index "${name}" n)

unset name;
echo ${name}

# use for
echo "for"
for((i=0; i<10; i++));
  do 
    echo ${i} 
  done

# use while 

